"""Routing decision logger with complexity scoring for ClearPath RAG Chatbot."""
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, Optional
from logging.handlers import TimedRotatingFileHandler

logger = logging.getLogger(__name__)


class RoutingLogger:
    """Logger for routing decisions with complexity scoring and daily rotation."""
    
    def __init__(self, log_file_path: str = "logs/routing_decisions.jsonl"):
        """
        Initialize the routing logger.
        
        Args:
            log_file_path: Path to the log file (default: logs/routing_decisions.jsonl)
        """
        self.log_file_path = Path(log_file_path)
        
        # Ensure log directory exists
        self.log_file_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Set up file handler with daily rotation
        self.file_handler = TimedRotatingFileHandler(
            filename=str(self.log_file_path),
            when='midnight',  # Rotate at midnight
            interval=1,  # Every 1 day
            backupCount=30,  # Keep 30 days of logs
            encoding='utf-8'
        )
        
        # Set up logger
        self.logger = logging.getLogger('routing_logger')
        self.logger.setLevel(logging.INFO)
        self.logger.addHandler(self.file_handler)
        self.logger.propagate = False  # Don't propagate to root logger
    
    def log_routing_decision(
        self,
        query: str,
        classification: str,
        model_used: str,
        tokens_input: int,
        tokens_output: int,
        latency_ms: int,
        rule_triggered: str,
        complexity_score: Dict[str, int],
        chunks_retrieved: int = 0,
        evaluator_flags: Optional[list] = None,
        system_prompt_tokens: int = 0,
        context_tokens: int = 0
    ) -> None:
        """
        Log a routing decision with full metadata.
        
        Args:
            query: The user query text
            classification: Classification result ("simple" or "complex")
            model_used: The LLM model used for generation
            tokens_input: Total input tokens sent to LLM
            tokens_output: Total output tokens generated by LLM
            latency_ms: Total latency in milliseconds
            rule_triggered: Which decision tree rule was applied
            complexity_score: Dictionary with complexity metrics
            chunks_retrieved: Number of chunks retrieved (default: 0)
            evaluator_flags: List of evaluator flags raised (default: [])
            system_prompt_tokens: Tokens used by system prompt (default: 0)
            context_tokens: Tokens used by context chunks (default: 0)
        """
        if evaluator_flags is None:
            evaluator_flags = []
        
        log_entry: Dict[str, Any] = {
            "timestamp": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
            "query": query,
            "classification": classification,
            "model_used": model_used,
            "rule_triggered": rule_triggered,
            "complexity_score": complexity_score,
            "tokens_input": tokens_input,
            "tokens_output": tokens_output,
            "system_prompt_tokens": system_prompt_tokens,
            "context_tokens": context_tokens,
            "latency_ms": latency_ms,
            "chunks_retrieved": chunks_retrieved,
            "evaluator_flags": evaluator_flags
        }
        
        # Write as JSON Lines format (one JSON object per line)
        self.logger.info(json.dumps(log_entry))
        
        # Also log to console for debugging
        logger.debug(
            f"Routing decision logged: {classification} -> {model_used} "
            f"(rule: {rule_triggered}, tokens: {tokens_input}/{tokens_output}, "
            f"latency: {latency_ms}ms)"
        )
    
    def close(self) -> None:
        """Close the file handler."""
        self.file_handler.close()
        self.logger.removeHandler(self.file_handler)
