"""API request and response models for the ClearPath RAG Chatbot."""
from typing import List, Optional
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """Request model for POST /query endpoint."""
    question: str = Field(..., min_length=1, max_length=1000, description="User question")
    conversation_id: Optional[str] = Field(None, description="Optional conversation ID for multi-turn conversations")


class TokenUsage(BaseModel):
    """Token usage breakdown for a query."""
    input: int = Field(..., description="Number of input tokens sent to LLM")
    output: int = Field(..., description="Number of output tokens generated by LLM")


class ResponseMetadata(BaseModel):
    """Metadata about query processing."""
    model_used: str = Field(..., description="LLM model used for generation")
    classification: str = Field(..., description="Query classification (simple or complex)")
    tokens: TokenUsage = Field(..., description="Token usage breakdown")
    latency_ms: int = Field(..., description="Total processing time in milliseconds")
    chunks_retrieved: int = Field(..., description="Number of document chunks retrieved")
    evaluator_flags: List[str] = Field(default_factory=list, description="Quality warning flags")


class Source(BaseModel):
    """Source document reference."""
    document: str = Field(..., description="Document filename")
    page: Optional[int] = Field(None, description="Page number in document")
    relevance_score: Optional[float] = Field(None, description="Relevance score (0-1)")


class QueryResponse(BaseModel):
    """Response model for POST /query endpoint."""
    answer: str = Field(..., description="Generated answer to the user's question")
    metadata: ResponseMetadata = Field(..., description="Query processing metadata")
    sources: List[Source] = Field(default_factory=list, description="Source documents used")
    conversation_id: str = Field(..., description="Conversation ID for this exchange")
