"""API request and response models for the Intelligent RAG pipeline."""
from typing import List, Optional

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """Request model for POST /query endpoint."""
    question: str = Field(..., min_length=1, max_length=1000, description="User question")
    conversation_id: Optional[str] = Field(None, description="Optional conversation ID for multi-turn conversations")


class TokenUsage(BaseModel):
    """Token usage breakdown for a query."""
    input: int = Field(..., description="Number of input tokens sent to LLM")
    output: int = Field(..., description="Number of output tokens generated by LLM")


class ResponseMetadata(BaseModel):
    """Metadata about query processing."""
    model_used: str = Field(..., description="LLM model used for generation")
    classification: str = Field(..., description="Query classification (simple or complex)")
    tokens: TokenUsage = Field(..., description="Token usage breakdown")
    latency_ms: int = Field(..., description="Total processing time in milliseconds")
    chunks_retrieved: int = Field(..., description="Number of document chunks retrieved")
    evaluator_flags: List[str] = Field(default_factory=list, description="Quality warning flags")


class Source(BaseModel):
    """Source document reference."""
    document: str = Field(..., description="Document filename")
    page: Optional[int] = Field(None, description="Page number in document")
    relevance_score: Optional[float] = Field(None, description="Relevance score (0-1)")


class QueryResponse(BaseModel):
    """Response model for POST /query endpoint."""
    answer: str = Field(..., description="Generated answer to the user's question")
    metadata: ResponseMetadata = Field(..., description="Query processing metadata")
    sources: List[Source] = Field(default_factory=list, description="Source documents used")
    conversation_id: str = Field(..., description="Conversation ID for this exchange")


class UploadFileResult(BaseModel):
    """Result for a single uploaded file."""
    filename: str = Field(..., description="Name of the uploaded file")
    pages: int = Field(0, description="Number of pages extracted")
    chunks: int = Field(0, description="Number of chunks created")
    status: str = Field(..., description="Processing status: success or error")
    error: Optional[str] = Field(None, description="Error message if processing failed")


class UploadResponse(BaseModel):
    """Response model for POST /upload endpoint."""
    files: List[UploadFileResult] = Field(..., description="Results per file")
    total_chunks: int = Field(..., description="Total chunks created across all files")
    total_pages: int = Field(..., description="Total pages processed across all files")
    latency_ms: int = Field(..., description="Total processing time in milliseconds")


# --- Video Semantic Search API models (separate from document RAG) ---


class VideoUploadResponse(BaseModel):
    """Response for POST /videos/upload (202 Accepted)."""
    video_id: str = Field(..., description="Unique video identifier")
    job_id: Optional[str] = Field(None, description="Processing job id if async")
    message: str = Field(..., description="Status message")
    original_filename: str = Field(..., description="Original file name")


class VideoStatusResponse(BaseModel):
    """Response for GET /videos/{video_id}/status."""
    video_id: str
    status: str = Field(..., description="pending | processing | processed | failed")
    progress: Optional[float] = Field(None, description="0-1 if processing")
    error: Optional[str] = Field(None, description="Error message if failed")


class VideoSearchRequest(BaseModel):
    """Request for POST /videos/search."""
    query: str = Field(..., min_length=1, max_length=1000)
    top_k: int = Field(10, ge=1, le=50)


class VideoSearchResultItem(BaseModel):
    """Single frame in video search results."""
    frame_id: str
    video_id: str
    timestamp_sec: float
    frame_path: str
    thumbnail_url: str = Field(..., description="URL to fetch thumbnail image")
    video_url: str = Field(..., description="URL to stream video for player")
    similarity: float


class VideoSearchResponse(BaseModel):
    """Response for POST /videos/search."""
    results: List["VideoSearchResultItem"] = Field(default_factory=list)


# --- Image Semantic Search API models (separate from video/document RAG) ---


class ImageUploadResponse(BaseModel):
    """Response for POST /images/upload (202 Accepted)."""
    image_id: str = Field(..., description="Unique image identifier")
    job_id: Optional[str] = Field(None, description="Processing job id if async")
    message: str = Field(..., description="Status message")
    original_filename: str = Field(..., description="Original file name")


class ImageStatusResponse(BaseModel):
    """Response for GET /images/{image_id}/status."""
    image_id: str
    status: str = Field(..., description="pending | processing | processed | failed")
    error: Optional[str] = Field(None, description="Error message if failed")


class ImageSearchRequest(BaseModel):
    """Request for POST /images/search."""
    query: str = Field(..., min_length=1, max_length=1000)
    top_k: int = Field(10, ge=1, le=50)


class ImageSearchResultItem(BaseModel):
    """Single image search result."""
    image_id: str
    image_path: str
    thumbnail_url: str = Field(..., description="URL to fetch thumbnail image")
    image_url: str = Field(..., description="URL to fetch original image")
    similarity: float


class ImageSearchResponse(BaseModel):
    """Response for POST /images/search."""
    results: List["ImageSearchResultItem"] = Field(default_factory=list)


class ImageListItem(BaseModel):
    """Info about a single image in the store."""
    image_id: str
    original_filename: str
    status: str
    file_size_bytes: Optional[int] = None


class ImagesListResponse(BaseModel):
    """Response for GET /images."""
    images: List[ImageListItem] = Field(default_factory=list)
    total_images: int = Field(0)


class VideoListItem(BaseModel):
    """Info about a single video in the store."""
    video_id: str
    original_filename: str
    status: str
    file_size_bytes: Optional[int] = None
    frame_count: int = 0


class VideosListResponse(BaseModel):
    """Response for GET /videos."""
    videos: List[VideoListItem] = Field(default_factory=list)
    total_videos: int = Field(0)


class DocumentInfo(BaseModel):
    """Info about a single document in the vector store."""
    document_name: str = Field(..., description="Document filename")
    chunk_count: int = Field(..., description="Number of chunks stored")
    page_count: int = Field(..., description="Number of pages")


class DocumentsListResponse(BaseModel):
    """Response model for GET /documents endpoint."""
    documents: List[DocumentInfo] = Field(..., description="All documents in the vector store")
    total_documents: int = Field(..., description="Total number of documents")
    total_chunks: int = Field(..., description="Total chunks across all documents")


class DeleteDocumentResponse(BaseModel):
    """Response model for DELETE /documents/{name} endpoint."""
    document_name: str = Field(..., description="Deleted document name")
    chunks_deleted: int = Field(..., description="Number of chunks removed")
    status: str = Field(..., description="Deletion status")
